### ISSUE TITLE
False positive triggers and other wrong behavior 

### ISSUE THREAD

**Issue by magico13** [AudDMusic/RedditBot#3]
You may already be aware of this if you're looking through the bot's comments but rather than just downvoting I figured I'd make an issue so you can look into it. Link below, but I have no idea how/why it matched this.

https://www.reddit.com/r/KerbalSpaceProgram/comments/oeu8mg/lets_get_some_heavy_machinery_on_the_surface_and/h48swh6

**Comment by Mihonarium** [comment]
Thank you!

That's really strange. I have no idea how could "Great job!" trigger the bot. 

And I also don't know why it posted the _"If the matched percent is less than 100..."_ thing with a 100% match.

If it were the first thing only, I would think that's a Reddit bug (something with comment IDs). If it were the second thing only, I'd think a bit randomly changed in the server's RAM or something: it's unlikely, but not impossible. But because there are two, I don't understand how it's possible. I should probably turn the logs back on.

**Comment by Mihonarium** [comment]
The bot [continues](https://www.reddit.com/r/nextfuckinglevel/comments/l5jed4/stumbled_upon_this_12_year_old_drummer_what_the/h4b1bmm/?utm_source=reddit&utm_medium=web2x&context=3) posting the "If the matched percent is less than 100..." thing with 100% matches, so I decided to shut down the bot.

If anyone could look at the code, that would be highly appreciated.

**Comment by Mihonarium** [comment]
Don't notice the bug appearing, so closing the issue. It was probably something on the Reddit's side
