### ISSUE TITLE
Bot replies when it cannot identify a song.

### ISSUE THREAD

**Issue by GarrettBlackmon** [AudDMusic/RedditBot#9]
"What song is this?"

"idk"

**Comment by Mihonarium** [comment]
It does reply that it can't identify the song when someone summoned it with a mention. But responding to comments asking for the song when the bot doesn't know the answer would add a lot of spammy "idk" replies, so I'm not sure why would it be helpful

**Comment by GarrettBlackmon** [comment]
@Mihonarium The current behavior is that it does reply with "idk" even on comments which  did not directly summon the bot. As you said, it's a bit spammy.

Here's an example: https://www.reddit.com/r/Chadtopia/comments/rwgs68/-/hrc3br3

**Comment by Mihonarium** [comment]
0_0 that's strange, thanks! I'll look into this

**Comment by Mihonarium** [comment]
From what I see in the code and the config, it doesn't look like it was possible for the bot to reply there. And I couldn't find any other replies like that one, even though there are thousands of comments the bot doesn't reply to because it couldn't identify the song. Are there other examples?

The config has ReplySettings -> comment -> ReplyAlways as false, so unless Reddit sends the comment to the bot as a mention or the comment body contains "auddbot" or "recognizesong", the return at https://github.com/AudDMusic/RedditBot/blob/main/main.go#L670 should happen, and the bot can't send the IDK reply.

The comment doesn't show up as edited, so it's likely a random bit flip or a compiler-level bug unless I'm missing something.

**Comment by Mihonarium** [comment]
Please reopen the issue or create a new one if you notice this behavior.
